# Uncomment the next line to define a global platform for your project
# platform :ios, '12.4'

target 'Paint_Recommend' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Paint_Recommend
  pod 'SwiftyJSON'
  pod 'MarqueeLabel'

  target 'Paint_RecommendTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Paint_RecommendUITests' do
    # Pods for testing
  end

end
